services:
  next-app:
    image: node:20-bullseye-slim
    command: [npm, run, debug]
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 3000:3000
      - 9229:9229
      - 9230:9230
